### ISSUE TITLE
Token Research Agent

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/AutoTx#96]
Develop a "token research" agent that enables users to query various aspects of the token marketplace at large. It should leverage a cryptocurrency data platform like coingecko.com, and be able to respond to prompts such as:
* "What are the top 5 DePin tokens right now?"
  * details: search for tokens by category "DePin", sort tokens by market cap, return top 5 results.
* "Where can I buy BRETT?"
  * details: search for the BRETT token, see what chains or exchanges have this token listed, return results.
* "What is Polkadot's token?"
  * details: search for token by name, return its symbol and other cursory information that's readily available (description, price, mcap, etc).
* "What are the top 5 tokens on Base chain?"
  * details: search for top mcap tokens on a specific chain, return top 5 results.
* "How much liquidity does UNI have?"
  * details: return total liquidity for UNI in all markets.
* "What's the 24hr trading volume of ETH?"
* "What's the 24 hour price change of ETH?"
* "What's the 7 day price change of ETH?"

More advanced prompts:
* "Buy me 5 small cap AI tokens that have a high chance of blowing up this week"
  * details: find small mcap AI tokens, see which ones have a high price change & trading volume, buy the top 5.
* "Send a meme coin to vitalik.eth"
  * details: lookup what meme coins exist, see which ones the user owns, if none try to buy the most popular, send to vitalik.eth
  
When finding an API to use, we should try to optimize for quality of features, and price. Ideally it wouldn't cost too much $ so users could easily signup for their own API keys. Please reference the following links when making this decision:
* https://www.coingecko.com/en/api
* https://tokenterminal.com/
* https://messari.io/api
* https://moralis.io/
* https://coinmarketcap.com/api/
* https://www.alchemy.com/alternatives/coingecko-api
* https://www.tokenmetrics.com/blog/best-cryptocurrency-apis
* https://defillama.com/

**Comment by cbrzn** [comment]
# Token Research Tool API

## Selection criteria
- Functionality
    - Multiple tokens & chains
    - Liquidity of token
    - Historical prices
    - Categorize tokens
- API Key easy to access
- Cheap to use

### Candidates

#### Messari
- [API only available to Enterprise users](https://docs.messari.io/reference/authentication), which makes on boarding ux very bad
- They have governance information which might come handy when we want to support dao research

#### Defillama
- Doesn't need API Key (Until rate limit is reached which is not specified in their documentation)
- It uses coingecko under the hood
- Doesn't have token metadata (like market cap or how much was traded in the last 24 hours)
- Doesn't categorize tokens, because it's completely focused on Defi
- Information on yields, which might come handy when we want to support yield

#### Moralis
- Focused on wallet UX (Like getting all erc20 and nfts of an address), rather than token research per se
- Doesn't have token metadata (like market cap or how much was traded in the last 24 hours)
- Access tokens through address and not through symbol, making us to depend on another service to map symbol to address
- Only supports uniswap v2 when it comes to token liquidity

#### Tokenterminal
- [User needs to send an email to them in order to get an API Key](https://docs.tokenterminal.com/reference/api-reference), which makes on-boarding ux very bad
- The API does not have too much functionality

#### Coingecko
- Has a free tier plan, but has a rate limit of ~30 calls per minute (depends on traffic size according to documentation)
- Gives information about the historic price of tokens
- Allows to easily compare to any other currency (fiat or token)
- Has categories for tokens, allowing to query them based on chain/category
- Returns intervals of 24h/7d/14d/30d/60d/200d/1y for price change percentage

#### Coinmarketcap
- Has a free tier plan that allows 10k calls monthly
- Is very much like Coingecko with the difference that the free tier has fewer endpoints and returns less information when it comes to historical data
- Also, the max interval it returns is `90d`


### Conclusion

After considering the different options and their pros and cons, I suggest moving forward with Coingecko due to its complete feature with the free plan; we can do useful things with what's available

**Comment by dOrgJelli** [comment]
Fantastic breakdown sir! Let's move forward with Coingecko then 🔥
